# Dockerfile.jenkins-agent
FROM jenkins/jenkins:lts

USER root

# Install Docker CLI, Docker Compose, Node.js, Git, etc.
RUN apt-get update && \
    apt-get install -y \
    docker.io \
    docker-compose \
    git \
    curl \
    bash && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    usermod -aG docker jenkins && \
    apt-get clean

USER jenkins
