version: "3"

services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test-runner:
    build:
      context: .
    depends_on:
      - selenium-hub
      - chrome
    volumes:
      - /c/CLIENTS/Projects/selenium-js-docker-jenkins:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "tail -f /dev/null"

